### ISSUE TITLE
Published version of this repo does not work with web-only projects

### ISSUE THREAD

**Issue by roryabraham** [Expensify/react-native-onyx#201] opened 2022-10-15 15:21 UTC
### Problem
If you update a web-only (non-react-native) project using this repo to the latest published version, you will see that it doesn't work as expected, with lots of errors like this:

```
WARNING in ./src/pages/pair/comparison/ComparisonTable.js 267:15-23
export 'withOnyx' (imported as 'withOnyx') was not found in 'react-native-onyx' (possible exports: __esModule)
```

### Solution
Investigate and fix. The last version I _know_ worked was `git+https://github.com/Expensify/react-native-onyx.git#1e82e592032c6d0ede8e40f08beb6be790d149e8`

**Comment by roryabraham** [comment] 2022-10-15 15:21
cc @kidroca – any bandwidth to investigate?

**Comment by kidroca** [comment] 2022-10-17 09:43
Yep, I'll check it out

**Comment by roryabraham** [comment] 2022-10-17 21:28
Awesome, thanks!

**Comment by kidroca** [comment] 2022-10-19 13:22
I wasn't able to reproduce the problem on my web test project 
- using Create React App (CRA) (React 18.1)
- "react-native-onyx": "1.0.24"
- Node 16, npm 8.19.1

@roryabraham 
Can you tell me what bundler, react-native-onyx version and Nodejs version for the project getting the error?

**Comment by roryabraham** [comment] 2022-10-20 23:48
- webpack: `^5.21.2`
- react-nagive-onyx: `1.0.24`
- Node 14.20.0
- npm 6.14.17

**Comment by tgolen** [comment] 2022-10-27 16:43
I'm on the same versions as @roryabraham and seeing the same import errors.

**Comment by tgolen** [comment] 2022-10-27 16:45
This is the `package.json` that I'm using in one of our other repos:

<details>
<summary>package.json</summary>

```

{
  "private": true,
  "name": "comp",
  "scripts": {
    "preinstall": "./tools/checkRuntimeVersions.sh",
    "build": "webpack --config webpack.prod.js",
    "web": "webpack-dev-server --open --config webpack.dev.js",
    "fixPHP": "php tools/ci/stylephp.php",
    "test": "./tools/ci/tests.unit.sh",
    "createOrUpdateDB": "php scripts/createOrUpdateDatabaseSchema.php",
    "lint": "eslint . --max-warnings=0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Expensify/Comp.git"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "@babel/runtime": "^7.11.2",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.2",
    "html-webpack-plugin": "^5.0.0",
    "node-sass": "^5.0.0",
    "react-refresh": "^0.9.0",
    "sass-loader": "^11.0.1",
    "style-loader": "^2.0.0",
    "@svgr/webpack": "^5.5.0",
    "webpack": "^5.21.2",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^4.0.0-beta.0",
    "webpack-merge": "^5.7.3"
  },
  "dependencies": {
    "@babel/plugin-transform-runtime": "^7.12.15",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "classnames": "^2.3.1",
    "dotenv": "^8.2.0",
    "eslint-config-expensify": "^2.0.16",
    "eslint-loader": "^4.0.2",
    "expensify-common": "git+https://github.com/Expensify/expensify-common.git#e0ec0b9abca4d7b417ba0b016f8725856cfeeece",
    "jquery": "^3.4.1",
    "localforage": "^1.10.0",
    "lodash": "^4.17.21",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-native-config": "^1.4.2",
    "react-native-onyx": "1.0.24",
    "react-router-dom": "^5.1.2",
    "underscore": "^1.13.2"
  }
}

```
</details>

**Comment by kidroca** [comment] 2022-10-27 18:39
Here's is a webpack 5 project I used and got `ract-native-onyx` `1.0.24` working: https://github.com/kidroca/use-onyx-in-a-web-project-sample

**Comment by kidroca** [comment] 2022-10-27 18:52
Digging more into this it seems the problem is `react-native-onyx` is added to `babel-loader` include list (webpack config), like it was originally in App, before we started to bundle Onyx with Webpack

We had a similar issue on App: https://github.com/Expensify/App/issues/9163#issuecomment-1137336490

Related slack convo: https://expensify.slack.com/archives/C01GTK53T8Q/p1666895167441079?thread_ts=1666884616.336979&cid=C01GTK53T8Q

**Comment by AndrewGable** [comment] 2022-10-28 00:27
@kidroca figured out this was a webpack configuration issue on our side. Closing!

**Closed by AndrewGable** 2022-10-28 00:27 UTC

**Comment by tgolen** [comment] 2022-10-28 13:58
Yeah, you can see the solution in this PR:
https://github.com/Expensify/Comp/pull/356/files

**Comment by roryabraham** [comment] 2022-10-29 10:44
Thanks for working this out everyone!
